### ISSUE TITLE
配置流程说明建议

### ISSUE THREAD

**Issue by quaggalinux** [mritd/wol#1]
首先非常感谢您的创作!  
    
软件其实非常好用及简单.但是很多新上手的用户可能不容易摸索出一个简单的安装流程,因为说明不够,我这边摸索完了,有一个简单心得,如果作者不嫌弃,可以把我这个流程说明里面认为有用的部分加到你外面的readme.md里面,可能这样对推广有一些好处.  
  
运行wol生成样板配置文件,因为缺省情况下 wol 只读取 $HOME/.wol.yaml 配置文件(即当前登录用户自己的目录,如NAS设备登录是root用户,那么这个$HOME/目录表示/home/root/目录)   
  
#wol example > ~/.wol.yaml  
  
增加自己设备的参数到样板配置文件,机器名字pc可以随便命名,不过建议小写字母,因为linux大小写敏感,另外由于不确定程序大小写支持情况,所以MAC地址确保是大写!!!   
  
#wol add -n pc -m 00:F8:61:CD:A4:82  
  
唤醒指定机器名字  
  
#wol wake pc  
  
列出样板配置里面所有机器的列表  
  
#wol print  
  
删除样板配置缺省的无用机器参数  
  
#wol del iMac

**Comment by mritd** [comment]
感谢，没想到这么快被发现了，刚重写一遍，我有时间好好整理一下文档。

**Comment by mritd** [comment]
@quaggalinux 已经重新完善了文档，你看下是否还有需要改进的地方 😁

**Comment by quaggalinux** [comment]
基本很完美了 ㄟ(≧◇≦)ㄏ
